global:
    scrape_interval: 10s
    evaluation_interval: 10s

scrape_configs:
    -   job_name: 'playground'
        metrics_path: /actuator/prometheus
        static_configs:
            -   targets: [ 'localhost:8080' ]